# Generated by Django 5.1.2 on 2024-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomzodlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='ism familiya')),
                ('ovozlar', models.BigIntegerField(default=0, verbose_name='ovozlar soni')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=200, verbose_name='post rasmi')),
                ('caption', models.TextField(verbose_name='Post texti')),
                ('channel', models.CharField(blank=True, max_length=200, null=True)),
                ('nomzotlar', models.ManyToManyField(to='users.nomzodlar')),
            ],
        ),
    ]
