# Generated by Django 5.1.2 on 2024-11-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nomzodlar_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_id',
            field=models.CharField(blank=True, null=True, verbose_name='message id'),
        ),
    ]
