# Generated by Django 5.1.2 on 2024-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_id',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='message id'),
        ),
    ]
