# Generated by Django 5.1.2 on 2024-11-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_post_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, verbose_name='message id')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.post')),
            ],
        ),
    ]
