# Generated by Django 5.1.2 on 2024-11-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sendpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='sarlavha'),
            preserve_default=False,
        ),
    ]
