# Generated by Django 5.1.2 on 2024-11-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_post_date_time_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendpost',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
    ]
