# Generated by Django 5.1.2 on 2024-11-05 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_sendpost_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendpost',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sendpost',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
    ]
