# Generated by Django 5.1.2 on 2024-11-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_post_caption_alter_post_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
    ]
