# Generated by Django 5.1.2 on 2024-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nomzotlar',
        ),
        migrations.AddField(
            model_name='nomzodlar',
            name='posts',
            field=models.ManyToManyField(related_name='nomzodlar', to='users.post', verbose_name='posts'),
        ),
    ]
