# Generated by Django 5.1.2 on 2024-11-05 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_post_nomzotlar_nomzodlar_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.post', verbose_name='Post')),
                ('nomzodlar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.nomzodlar', verbose_name='Nomzodlar')),
            ],
        ),
    ]
