# Generated by Django 5.1.2 on 2024-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_history_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_post',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Ovozlar soni'),
        ),
    ]
