# Generated by Django 5.1.2 on 2024-11-05 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_history_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_post',
            name='nomzodlar',
        ),
        migrations.RemoveField(
            model_name='history_post',
            name='votes',
        ),
        migrations.AddField(
            model_name='history_post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history_post',
            name='history_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_posts', to='users.post', verbose_name='Post'),
        ),
    ]
