# Generated by Django 5.1.2 on 2024-11-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_history_post_nomzodlar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomzodlar',
            name='posts',
        ),
        migrations.AddField(
            model_name='nomzodlar',
            name='posts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nomzodlar', to='users.post'),
            preserve_default=False,
        ),
    ]
