# Generated by Django 5.1.2 on 2024-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_nomzodlar_posts_nomzodlar_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nomzodlarr',
            field=models.ManyToManyField(to='users.nomzodlar'),
        ),
    ]
