# Generated by Django 5.1.2 on 2024-11-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_post_nomzodlarr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_Post',
        ),
    ]
