# Generated by Django 5.1.2 on 2024-11-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_history_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nomzodlarr',
            new_name='nomzodlar',
        ),
        migrations.AlterField(
            model_name='nomzodlar',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomzodlars', to='users.post'),
        ),
    ]
