# Generated by Django 5.1.2 on 2024-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nomzodlar',
            field=models.ManyToManyField(blank=True, to='users.nomzodlar'),
        ),
    ]
