# Generated by Django 5.1.2 on 2024-11-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_post_nomzodlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomzod_ovozlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomzod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.nomzodlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
