# Generated by Django 5.1.2 on 2024-11-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_nomzod_ovozlari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nomzod_ovozlari',
            new_name='Nomzot_Ovozlar',
        ),
    ]
