# Generated by Django 5.1.2 on 2024-11-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_nomzod_ovozlari_nomzot_ovozlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomzot_ovozlar',
            name='nomzod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomzot_ovozlar', to='users.nomzodlar'),
        ),
    ]
