# Generated by Django 5.1.2 on 2024-11-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_nomzot_ovozlar_nomzod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomzodlar',
            name='ovozlar',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='ovozlar soni'),
        ),
        migrations.AlterUniqueTogether(
            name='nomzot_ovozlar',
            unique_together={('user', 'nomzod')},
        ),
    ]
