# Generated by Django 5.1.2 on 2024-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_nomzodlar_ovozlar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomzot_ovozlar',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nomzodlar',
            name='ovozlar',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='ovozlar soni'),
        ),
    ]
