# Generated by Django 5.1.2 on 2024-11-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_nomzot_ovozlar_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomzot_ovozlar',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='nomzot_ovozlars', to='users.post'),
            preserve_default=False,
        ),
    ]
