# Generated by Django 5.1.2 on 2024-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_nomzot_ovozlar_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomzot_ovozlar',
            name='user',
        ),
        migrations.AddField(
            model_name='nomzot_ovozlar',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram_id'),
        ),
    ]
