# Generated by Django 5.1.2 on 2024-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_nomzot_ovozlar_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomzot_ovozlar',
            name='telegram_id',
            field=models.BigIntegerField(default=1, verbose_name='Telegram_id'),
        ),
    ]
