# Generated by Django 5.1.2 on 2024-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_nomzot_ovozlar_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomzot_ovozlar',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Telegram_id'),
        ),
    ]
