# Generated by Django 5.1.2 on 2024-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_post_created_at_remove_post_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='message id'),
        ),
    ]
