# Generated by Django 5.1.2 on 2024-11-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_post_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomzot_ovozlar',
            name='nomzod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomzot_ovozlar', to='users.nomzodlar'),
        ),
        migrations.AlterField(
            model_name='nomzot_ovozlar',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nomzot_ovozlars', to='users.post'),
        ),
    ]
