# Generated by Django 5.1.2 on 2024-11-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_nomzot_ovozlar_nomzod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomzodlar',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nomzodlars', to='users.post'),
        ),
        migrations.AlterField(
            model_name='nomzot_ovozlar',
            name='nomzod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nomzot_ovozlar', to='users.nomzodlar'),
        ),
    ]
