# Generated by Django 5.1.2 on 2024-11-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_nomzot_ovozlar_nomzod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi va vaqti'),
        ),
    ]
